#!/bin/bash
set -veuxo pipefail

if ! [[ -z "$(git status -s -uall)" ]]; then
    echo "warning: index is already dirty"
    sleep 4
fi

bash scripts/generate
bash scripts/format

git add .

if ! [[ -z "$(git status -s -uall)" ]]; then    
    # copy message and authorship from current (parent) commit
    export GIT_AUTHOR_DATE="$(git log -1 --pretty=format:'%ad')"
    GIT_MESSAGE="$(git log -1 --pretty=%B)"

    # but use distinct committer and commit timestamp
    export GIT_COMMITTER_NAME="autofix"
    export GIT_COMMITTER_EMAIL="bot@jeremy.ca"

    git commit -m $"[autofix] ${GIT_MESSAGE}" --allow-empty-message

    git push
fi
