#!/bin/bash
set -veuxo pipefail

if ! [[ -z "$(git status -s -uall)" ]]; then
    echo "error: index is already dirty"
    exit
fi

git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
git pull github ${GITHUB_REF} --ff-only

bash scripts/generate
bash scripts/format

git add .

if ! [[ -z "$(git status -s -uall)" ]]; then    
    export GIT_AUTHOR_NAME="$(git log -1 --pretty=format:'%an')"
    export GIT_AUTHOR_EMAIL="$(git log -1 --pretty=format:'%ae')"
    export GIT_COMMITTER_NAME="a bot"
    export GIT_COMMITTER_EMAIL="bot@jeremy.ca"

    git commit -m "🛠 code generation and formatting for ${GITHUB_SHA}"

    git push github HEAD:${GITHUB_REF}
fi
