#!/bin/bash
set -veuxo pipefail

find . -name __generated__ -type d -exec rm -r {} +

cargo build --bin serve

cargo run --bin serve &
trap "kill $!" EXIT

sleep 2

apollo client:codegen --target typescript --globalTypesFile src/client/__generated__/globalTypes.d.ts
apollo client:download-schema src/client/__generated__/schema.graphql
